### ISSUE TITLE
How to build a index.html file like All Plots for use the new indicator like arron, demarker, ...

### ISSUE THREAD

**Issue by linuxorg1** [andredumas/techan.js#107]
Hi,
i modified index.html for "All Plots" and include Ichimoku for day and Hourly Charts. It works.
How can i build odr modified a index.html file to include the new indicator like  ADX,  Aroon,  Bollinger bands,  Stochastic oscillator , Williams %R and demarker.

I try it to modofy this File but the are some Problems like TypeError: arronScale is undefined.

With Best Regards

**Comment by andredumas** [comment]
Closing, not enough information and it doesn't appear to be an issue with the library.
