### ISSUE TITLE
TechanJS with Databases

### ISSUE THREAD

**Issue by lonnietc** [andredumas/techan.js#110]
Greetings,

I am a bit new to TechanJS, but would like to know if you have any code that would allow for pulling the data from a database?

I was looking at your example at:

http://bl.ocks.org/andredumas/edf630690c10b89be390

and it seems that the data is embedded. I would like to be able to access a database like mysql, mongodb, or something similar.

Could you please give me some guidance or possibly point me in the right direction so that I can try to locate some code that might be integrated into TechanJS for the above example?

Thanks and Happy New Year,
Lonnie

**Comment by wenn32** [comment]
Greetings Lonnie,

I am not developer of this application but just wanted to share my view.
As far as I am aware you can't do direct DB access using browser you need a web service in between to accomplish this.

This web service can parse the data to CSV and can be directly read by the D3.CSV() method.

Hope this helps.

Happy New year.
Wenn

**Comment by kaffeebrauer** [comment]
Hi Lonnie,

You would need to return the data in the form of a Json.

```
var parseDate = d3.time.format("%d-%b-%y").parse;

var data= $rootScope.prices;
            data= data.map(function (d) {
                return {
                    date: parseDate(d.date),
                    open: +d.open,
                    high: +d.high,
                    low: +d.low,
                    close: +d.close,
                    volume: +d.volume
                };
            }).sort(function (a, b) { return d3.ascending(accessor.d(a), accessor.d(b)); });
```

The data for this example $rootScope.prices would look something similar to this

    var data = [
            { date: "9-Jun-14", open: 62.40, high: 63.34, low: 61.79, close: 62.88, volume: 37617413 },
            { date: "6-Jun-14",open: 63.37, high: 63.48, low: 62.15, close: 62.50,volume: 42442096 },
            { date: "5-Jun-14",open: 63.66, high: 64.36, low: 62.82, close: 63.19,volume: 47352368 },
            { date: "4-Jun-14",open: 62.45, high: 63.59, low: 62.07, close: 63.34,volume: 36513991 },
            { date: "3-Jun-14",open: 62.62, high: 63.42, low: 62.32, close: 62.87,volume: 32216707 },
            { date: "2-Jun-14",open: 63.23, high: 63.59, low: 62.05, close: 63.08,volume: 35995537 },
            { date: "30-May-14",open: 63.95, high: 64.17, low: 62.56, close: 63.30,volume: 45283577 }
        ]

**Comment by andredumas** [comment]
Hi @lonnietc 

There are a number of ways to do it, that example hints at one possible solution. The data is not embedded, it is coming from a [http end point](http://bl.ocks.org/andredumas/raw/edf630690c10b89be390/64c67474c23c7ca6cffe0de78d05e6ca98799aa1/data.csv). As @wenn32 and @kaffeebrauer mentioned you could create a http end point that returns the data from your database. Even easier if your datasource exposes a http api. d3 has a number of [request helpers](https://github.com/d3/d3/blob/master/API.md#requests-d3-request) out of the box which make integration simpler.

Closing the issue it's more a general question not specific to the library.

cheers
andre
