### ISSUE TITLE
How to set brush by first and last date

### ISSUE THREAD

**Issue by kallelzied** [andredumas/techan.js#112]
First thank you so much for the cool api,
Second Currently I'm implementing this http://bl.ocks.org/andredumas/a5acb93bae58f0805b53, but with a bit of react. my pb is i want to give the user a way to select a brush by a first and a last date, without doing a mouse select, is it possible?

Thanks!

**Comment by andredumas** [comment]
Hey @jonathanstrong, thanks for the response and that's a good way to do it. I've never tried that but it should work. As you mentioned financetime is a (irregular) date/time based scale and financetime.zoomable() is the index based scale of the underlying array.
