### ISSUE TITLE
Padding on Y Axis

### ISSUE THREAD

**Issue by dcgirl** [andredumas/techan.js#113]
Hi - first, what a wonderful app, I've been able to do almost everything I need with it. My question is about adding padding to the Y axis. Typically I can pad the domain in d3 to add space above and below the data that renders in the plot. I can't figure out how to do that with techan, I think I need to do it here: y.domain(techan.scale.plot.ohlc(data.slice(indicatorPreRoll)).domain());, but nothing I try works.

I'm getting around it right now by adding blank rectangles above and below the plot, and using borders to look like axes and making the real axes transparent, so it looks like there's padding. But it would be great if I could do this the right way.

Thanks for your help!

**Comment by priikone** [comment]
+1 for this.  The only way I've discovered how to make this happen is to add extra data to the domain, but this is not optimal solution.  It should work by specifying number of padding pixels for the axis.  In any case, if you want to try the domain trick, you could do something like this:

```
	var ydomain = techan.scale.plot.ohlc(data).domain();
	ydomain[0] -= padding;
	ydomain[1] += padding;
	y.domain(ydomain);
```

**Comment by efrister** [comment]
+ 1 for this from me as well. Using @priikone's suggestion works, but it's definitely not ideal...

**Comment by priikone** [comment]
Just an update, here's a proper way of doing it:

  y.domain(y.range().map(widen_y(chartHeight, top_padding, bottom_padding)).map(y.invert));

The height values would be percents of the chartHeight, like .1 for 10%.

And widen_y() is:

    function widen_y(height, wide1, wide2) {
	wide1 = height * wide1;
	wide2 = height * wide2;
	return function(d, i, array) {
	    if (i == 0)
		return wide1 ? d - (i * 2 - 1) * 1 * wide1 : d;
	    return wide2 ? d - (i * 2 - 1) * 1 * wide2 : d;
	};
    }

**Comment by andredumas** [comment]
The helpers for scale `techan.scale.plot.ohlc(data)` are basic helpers which provide 'sensible' (what works for me) defaults. If more padding is required, for now you can either take techan's result and add more as @priikone suggested, or generate your own extents.

The question could be asked if you're plotting charts in pure d3, how would you add padding to a domain?
