### ISSUE TITLE
Heikin Ashi Chart

### ISSUE THREAD

**Issue by elitely** [andredumas/techan.js#115]
Hi andredumas,

Thank you for developing 'techan.js'. It is a cool js script.

Just a request.....If it is possible,then please,add "Heikin Ashi" candlestick chart. It is another type of candlestick chart,used heavily by Technical analysts.

Thank you,again.

**Comment by MartinSeeler** [comment]
Why not using heikin ashi candlestick data as normal candlestick chart? It's the same chart type, you only have to calculate it by yourself.

**Comment by andredumas** [comment]
How far did you get with this? If you have the algorithm could be added in.

**Comment by neopunisher** [comment]
http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:heikin_ashi

**Comment by andredumas** [comment]
> ...you only have to calculate it by yourself

I was hoping after @MartinSeeler's comment there would be more than a link, like some code to share

**Comment by MartinSeeler** [comment]
The initial Heikin Ashi Candle can be easily mapped from a default Candle (or OHLC type):
Assume `currentCandle` is the real candle, the formula is
```js
var open = (currentCandle.open + currentCandle.close) / 2.0
var close = (currentCandle.open + currentCandle.high + currentCandle.low + currentCandle.close) / 4.0
var high = _.max([open, close, currentCandle.high])
var low = _.min([open, close, currentCandle.low])
```

After the initial Heikin Ashi Candle, all following Heikin Ashi Candles need the previous Heikin Ashi Candle as well, which uses the following formula:

```js
var open = (prevHeikinCandle.open + prevHeikinCandle.close) / 2.0
var close = (currentCandle.open + currentCandle.high + currentCandle.low + currentCandle.close) / 4.0
var high = _.max([open, close, currentCandle.high])
var lowAsk = _.min([open, close, currentCandle.low])
```

**Comment by andredumas** [comment]
Thanks @MartinSeeler, makes it much easier to drop it in.

Question: so this is not an indicator as such, but a data preprocessor and that all indicators and analysis will be performed on this processed data set and not on the base ohlc?
