### ISSUE TITLE
Real-Time Update 

### ISSUE THREAD

**Issue by ineffablep** [andredumas/techan.js#116]
Hi,. 
It is really a great chart library, thank you very much for making it open source.

Do you have any example to update chart on real-time data continuously running on prices.

Also is it possible to add Context Menu at points.

**Comment by dimitrovs** [comment]
+1

**Comment by albertosantini** [comment]
In Examples Gallery [1] there is the Feed example [2]

There is also Argo [3], a web app for the Forex market

[1] https://github.com/andredumas/techan.js/wiki/Gallery 
[2] http://bl.ocks.org/andredumas/95f1f22130fb1a3a8181
[3] http://argo.js.org/

**Comment by andredumas** [comment]
Thanks for covering this one @albertosantini

**Comment by jiminssyspire** [comment]
The feed example mentioned here seems to only update bar at a time. I guess techan does not support real-time updates on candles where the candle moves up and down until it is closed in which case the next candle moves up and down?

**Comment by Kurdiez** [comment]
The feed example mentioned here seems to only update bar at a time. I guess techan does not support real-time updates on candles where the candle moves up and down until it is closed in which case the next candle moves up and down?

**Comment by albertosantini** [comment]
Yes, you can.

You need to update the closing value of the last bar, tick by tick. 

Basically you update the last bar, changing only the closing value.
