### ISSUE TITLE
Zoom reset after Dynamic Update

### ISSUE THREAD

**Issue by dhakadamit** [andredumas/techan.js#117]
There was a same issue reported earlier and closed due to inactivity. Hence, creating a new one.

I am building real-time charts with dynamic update, but every time dataset is updated, zoom is reset to 1

I have seen one recommendation to cache the zoom settings and reapply them after redrawing. I have tried everything, but just can't seem to get it working.

Request you please post an example

**Comment by andredumas** [comment]
Refer to the example:
https://gist.github.com/andredumas/95f1f22130fb1a3a8181#file-index-html-L233

Start with the example and play around with that particular line:

```javascript
x.zoomable().domain(<cached display index array>);
```
