### ISSUE TITLE
Panning within limits

### ISSUE THREAD

**Issue by dhakadamit** [andredumas/techan.js#118]
When panning, provide an upper limit for both XAxis and YAxis

Have managed to do it for Yaxis with the following code

```
        if (y.domain()[0] < ymin) {
            zoom.translate([zoom.translate()[0], zoom.translate()[1] - y(ymin) + y.range()[0]]);
        } else if (y.domain()[1] > ymax) {
            zoom.translate([zoom.translate()[0], zoom.translate()[1] - y(ymax) + y.range()[1]]);
        }
```

But can't seem to get the same thing going for X-Axis. It seems like an issue with D3 itself. Has anyone managed to get it working?

Could you please post an example?

**Comment by andredumas** [comment]
Not enough information. Probably more a question for stackoverflow or similar than here.

**Comment by moon47usaco** [comment]
I would like this as well. I do not want the chart to be able to pan past the data. or at least not by say 10-20 bars in the future and not ever before the first bar. Currently you can pan the data completely out of frame leaving a blank chart. Is there a way to resolve that?

**Comment by andredumas** [comment]
Check new d3 api: https://github.com/d3/d3-zoom#zoom_translateExtent

I think that is what you want.
