### ISSUE TITLE
frequent 'aw, snap!' chrome crashes

### ISSUE THREAD

**Issue by jonathanstrong** [andredumas/techan.js#123]
I have eight OHLC charts built with techan.js, each with a brush zoom, and a global brush zoom that controls all of them. It's awesome. However, I frequently crash Chrome, getting the "Aw, Snap!" page. 

Is this expected from what I am doing? I understand I'm pushing the limits here of what a browser can handle. However, are there any tips for how to mitigate this? Thanks for any help you can provide.

**Comment by taivo1** [comment]
Actually same problem happens with the examples gallery if zoom/drag the chart chrome tends to crash. And the other browsers seem to render the svg quite slowly. This totally makes the library unusable for me :(

**Comment by albertosantini** [comment]
I don't think it is related with the lib per se.
I noticed the issue with the recent versions of Chrome (since 49?).

With Firefox or IE Edge, it seems my app works ok.

I think it is due to the graphics card, GPU and Chrome compatibility.
Try to disable via flags the GPU use.

**Comment by andredumas** [comment]
Thanks for the response @albertosantini. I've noticed similar in that past if I had multiple tabs open on different charts I would randomly get a chrome snap. I looked into it briefly but it went away after a chrome update.

Will close this for now, reopen if it's still an issue.
