### ISSUE TITLE
Data structure in different order..

### ISSUE THREAD

**Issue by cube60** [andredumas/techan.js#124]
I do know that the basic data structure required is: 
```
{
        date: new Date(2014, 2, 11),
        open: 12.3,
        high: 12.45,
        low: 12.22,
        close: 12.25
        volume: 1987289
    }
```
What if my data stream comes in as...
`date,CLOSE,high,low,OPEN,volume`

Can I rearrange the way the script looks for the order of data? How can I do this?

Thanks.

**Comment by jonathanstrong** [comment]
The data is expected to be an array of objects. The keys of the object have no meaningful order in this context because they will be called by name. As long as the names of the attributes are open, high, low, close, volume, an accessor that calls for those attributes will be fine.

**Comment by andredumas** [comment]
Thanks @jonathanstrong
