### ISSUE TITLE
Publish to npm registry

### ISSUE THREAD

**Issue by SummerWish** [andredumas/techan.js#128]
In China, we have npm mirrors but GitHub is not accessible. It would be much more convenient for us if you could publish the project to the npm registry, eg, "techan.js". Thanks!

**Comment by andredumas** [comment]
Hi @SummerWish 

Sorry for the late response, yes that was always the intent. 

regards
andre

**Comment by andredumas** [comment]
published to https://www.npmjs.com/package/techan

```
npm install techan
```

**Comment by breeswish** [comment]
Thanks, that's great!
