### ISSUE TITLE
Make plots compatible with d3 scales

### ISSUE THREAD

**Issue by andredumas** [andredumas/techan.js#13]
These plots are not compatible with d3 scales:
* [candlestick 1](https://github.com/andredumas/techan.js/blob/83008de7d2bbd0585e87644666cea0810a31070b/src/plot/candlestick.js#L46), [candlestick 2](https://github.com/andredumas/techan.js/blob/83008de7d2bbd0585e87644666cea0810a31070b/src/plot/candlestick.js#L72)
* [macd](https://github.com/andredumas/techan.js/blob/0ab9ecf0d5d6e94930a2c18459fb51fd89973d3b/src/plot/macd.js#L46)
* [ohlc](https://github.com/andredumas/techan.js/blob/83008de7d2bbd0585e87644666cea0810a31070b/src/plot/ohlc.js#L33)
* [volume](https://github.com/andredumas/techan.js/blob/0ab9ecf0d5d6e94930a2c18459fb51fd89973d3b/src/plot/volume.js#L42)

For plots with width, allow them to be user specified, or calculated by d3?

**Comment by andredumas** [comment]
I'm thinking of updating these plots with a `width([calculator])` that either gets or sets a function which returns the width of each element for the given plot. Allowing the user to define padding, etc.

Also part of this change is to move [this logic](https://github.com/andredumas/techan.js/blob/e97cae7abd9e2d9216215d1f675ef15bccedea77/src/scale/financetime.js#L203) somewhere more central which supports auto detection of techanjs scale vs d3 scale, but applies the same calculation.

**Comment by thomashan** [comment]
Hi Andre.
Does the zoomable plots work with the d3 time scale?
It seems to work for static plots (e.g. not zoomable) but doesn't work for zoomable plots.

**Comment by andredumas** [comment]
Example coming... `zoomable` is a techan thing. If you remove that and ensure the d3 scale is initialised with a 2 element array rather than all elements, that should be it.
