### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by chrisabrams** [andredumas/techan.js#130]
@andredumas you've done a great job with the project. are you still working on it?

**Comment by doonetheprune** [comment]
I have a feeling it might be

**Comment by andredumas** [comment]
Hi @chrisabrams 

It appears that way, but no, techan is not dead. My day job was incredibly busy the past 9 months or so and unfortunately did not allow time for anything else. This has now freed up and over the next few days I will go through the open issues and will work out where to take techan next.

Will close this on the next commit.

cheers
andre

**Comment by thomashan** [comment]
@andredumas AND he's back!

**Comment by chrisabrams** [comment]
GREAT NEWS :)
