### ISSUE TITLE
JS error when trying out "Complete Example"

### ISSUE THREAD

**Issue by dan-da** [andredumas/techan.js#133]
Trying the example from http://bl.ocks.org/andredumas/edf630690c10b89be390.

It works fine if I use the full data.csv, but if I remove data rows at the end it gives me an error:
```
Uncaught TypeError: Cannot read property 'close' of undefined
techan.js line 400
```

In particular, I see this error if the data.csv file has:  25 lines, 100 lines, 150 lines, 

The graph displays correctly with: 175 lines, 200 lines.

This is 100% reproduceable every time on my system in both chrome and firefox.

**Comment by andredumas** [comment]
The example is simple and expects the data to contain a certain number of items to plot. It's not an error with the library.
