### ISSUE TITLE
More easy API to use techan.js?

### ISSUE THREAD

**Issue by leedstyh** [andredumas/techan.js#137]
Nice job on Techan.js.

But the API is not very friendly to use, people has to have a good knowledge of d3.js. I think the API useage like these would be very helpful. (Sorry for my bad English)

```
sma20 = techan.sma({
  period: 20,
  color: "green",
  type: "simple",
  ...
});

vol = techan.volume({
  ...
});

techan.Draw({
  root: "#chart",
  width: 300,
  height: 200,
  ...
}).addIndicator(sma20)
  .addIndicator(vol).
  ...

```

**Comment by andredumas** [comment]
> people has to have a good knowledge of d3.js

Yes that's a good starting point. From the project readme:

> TechanJS utilises D3's [reusable chart API](https://bost.ocks.org/mike/chart/) pattern...

What you're asking is currently not the intent of techan. It might be in the future such as a layout generator, but the API will closely mirror d3. 

Feel free to seed a project that wraps techan in that API :thumbsup:
