### ISSUE TITLE
some part in plot area has hidden after update data and redraw

### ISSUE THREAD

**Issue by aim4u** [andredumas/techan.js#140]
I created three charts with another width or height and draw them.
It's good working.

But after quickly update data and redraw it, some part in plot area among them has hidden.
In debug mode if i follow its code slowly step by step, it does not reproduce.

Please check it, I don't know the reason.
Thanks.

**Comment by andredumas** [comment]
Hardly any detail here. jsfiddle, bl.ocks.org, screenshot?

I have no idea what to check based on the description :confused:

**Comment by aim4u** [comment]
<img src="http://103.60.126.12/images/disappear.png">

In red sqaure area, any vector has not displayed. Do you have any idea or check point ?

**Comment by aim4u** [comment]
At last the problem was solved.
I have some mistakes for the element id of svg.
