### ISSUE TITLE
Update to d3 4

### ISSUE THREAD

**Issue by andredumas** [andredumas/techan.js#141]
Update dependency to d3 v4.

## Potentially Breaking Changes
Changes were required to support this update:
* `axisannotations` cannot auto orient themselves as `d3.axis` no longer exposes `axis.orient()`. A member has been added so that `axisannotation.orient` exists with the same interface as d3.v3 `d3.svg.axis`. Defaults to `bottom`. Pass strings `top`, `bottom`, `left`, `right`. This may change in future. If either d3 exposes orient, or constructors may be added similar to new axis constructors: `axisannotationTop`
* `financetime.zoomable()` returns a persistent instance associated with the financetime. Previously was a new instance per call. To emulate previous functionality call `financetime.zoomable().copy()`

**Comment by aim4u** [comment]
If change d3 v4, happen 'the uncaught TypeError'.

Cannot read property 'linear' of undefined
Cannot read property 'format' of undefined

**Comment by gajus** [comment]
@andredumas is there a timeline for this?

**Comment by andredumas** [comment]
@gajus I haven't looked at what the impact will be, there's a few fundamental 'must have' features I'm getting through first to help increase coverage and ensure this cutover will be smooth.

**Comment by Silviu-Marian** [comment]
Do you need help?

**Comment by andredumas** [comment]
Yes, @Silviu-Marian, a check list of items would be great!

Some code would be awesome :smiley:

**Comment by Silviu-Marian** [comment]
Ha. Alright then, I'm looking into it. :)

**Comment by albertosantini** [comment]
I report a minimal analysis about update task.

After following `Build From Source` steps and checking the tests are passed, I changed `bower.json` and `package.json`: from `3.5.17` to `4.2.6`.

Main files and apis involved:
- `src\indicator\index.js` (only d3.max)
- `src\plot\index.js` (massive changes)
- `src\scale\financetime.js` (time apis)
- `src\scale\index.js` (scale apis)
- `svg\index.js` (only d3.functor)
- `src\util\index.js` (for d3.rebind)

Check also `test` folder.

See [Changes in D3 4.0](https://github.com/d3/d3/blob/master/CHANGES.md) for details.

A brief resumen.

- `d3.time.format("%c").parse` to `d3.timeParse("%c")`
- `d3.svg.line` to `d3.line`
- `d3.svg.area` to `d3.area`
- `d3.behavior.drag` to `d3.drag`
- In place of `d3.svg.axis` and axis.orient, D3 4.0 now provides four constructors for each orientation: `d3.axisTop`, `d3.axisRight`, `d3.axisBottom`, `d3.axisLeft`. 
- The `d3.functor` method has been removed. If you want to promote a constant value to a function, the recommended pattern is to implement a closure that returns the constant value.
- The method signature for optional accessors has been changed to be more consistent with array methods such as array.forEach: the accessor is passed the current element (d), the index (i), and the array (data), with this as undefined. This affects `d3.min`, `d3.max`, `d3.extent`, `d3.sum`, `d3.mean`, `d3.median`, `d3.quantile`, `d3.variance` and `d3.deviation`. 
- `d3.bisect`?
- `d3.mouse`?

Really I didn't apply any change locally.

I would like to understand if we may create an approach with incremental steps.
Maybe we may distribute the workload between the contributors and the main dev, speeding up this issue.

As we know, as [Argo](http://argo.js.org/) developer, I am interested to close this issue. :)

**Comment by andredumas** [comment]
This is awesome thanks @albertosantini!

In terms of approach, I'll roughly spike it using your summary to size things up. If it feels large I'll add tasks here or create additional issues and push work to a branch. If any others want to contribute that would be great. Would certainly speed things up.

**Comment by andredumas** [comment]
Actually made surprisingly good progress on this. Thanks again @albertosantini for the detailed summary. Definitely gave this task the kick start it needed.

All examples have been cut over as well.

Hopefully not too many issues coming out of this, extensive tests were definitely the hero of the day for this change.

**Comment by albertosantini** [comment]
@andredumas Thanks a lot for the effort.

I vote that commit as `Commit of The Year`. :)

Tested with Argo and it seems it works nice.

Thanks again!

**Comment by albertosantini** [comment]
This is how `techan 0.8.0` (d3 V4)  landed on my project:
https://github.com/albertosantini/argo/commit/0b26eab3e2279bfca607e079545a3bd5c7b4614f
https://github.com/albertosantini/argo/commit/c1e5b7119d08c8cebecb30cf45b3d9b9af6b7ff5

Hope that helps.
