### ISSUE TITLE
X Axis - Time interval API?

### ISSUE THREAD

**Issue by haoramirez** [andredumas/techan.js#144]
Hello,

First of all I just want to thank you for this incredibly useful library.

Secondly, I am having quite a bit of trouble figuring out how to specify the X-axis annotation. Some data has time correctly displayed ("8:05") and other times not (":05") and I was wondering if I could have greater control over which type is rendered, and how many to display at a time on the graph.

Thank you!

**Comment by andredumas** [comment]
> ...specify the X-axis annotation

Do you mean axis tick values and format? 

Yes this can be done. I've tried to mirror d3 api here, so you should have same flexibility. Sounds like you should be specifying your own [tickFormat](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Axes.md#tickFormat) and [ticks](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Axes.md#ticks) on the axis itself. The techanjs homepage uses axis.ticks to [dynamically adjust how many ticks to show based on screensize](https://github.com/andredumas/techan.js/blob/gh-pages/src/js/index.js#L224).
