### ISSUE TITLE
axis(x) right padding issue

### ISSUE THREAD

**Issue by medfxx** [andredumas/techan.js#148]
![figure](https://cloud.githubusercontent.com/assets/22093459/18378539/4640f4dc-7676-11e6-82b7-402d7559d149.jpg)

Hi;
I want to use ohlc(candlestick) chart like in picture.
How can set that.

**Comment by andredumas** [comment]
Both sides ( #11 `outerPadding`) or single side?

[This](https://gist.github.com/andredumas/ef212e7c26d2b7ba5403#file-index-html-L182) is how I do it single sided for [Ichimoku](http://bl.ocks.org/andredumas/ef212e7c26d2b7ba5403) sample. I use a zoom to move the chart across.
