### ISSUE TITLE
0.8.0 released, but not published

### ISSUE THREAD

**Issue by albertosantini** [andredumas/techan.js#156]
`0.8.0` release is not published on npm.

**Comment by andredumas** [comment]
Hi @albertosantini 

I've only created a 'development/pre' release 0.8.0-0. I normally don't publish these (on github releases or npm), they're only included in the repo directly and can be added via direct hash reference. 

I do this in bower.json to keep techanjs.org bleeding edge: 

```json
{
  "name": "techanjs-site",
  "dependencies": {
    "bootstrap": "3.3.1",
    "jquery": "1.11.0",
    "techan": "techan#b4b7c467dcba6040df964e3995bb2b5720f7f245"
}
```

I will probably release 0.8.0 today with only the d3 update included. Given the potential impact of this change it's probably best not to introduce too many variables.

andre

**Comment by albertosantini** [comment]
I see.

Thanks for the tip.
