### ISSUE TITLE
Zoom question

### ISSUE THREAD

**Issue by samweatherly** [andredumas/techan.js#157]
Hello,
I hope questions are OK here. I'm not sure if this is techan or d3 specific.
I am using a candlestick graph which is altered from this (http://bl.ocks.org/andredumas/a48008ea8e2c832144db) example to use my own data. 
On load, I want the graph to show/zoom to the last 30 days (or 30 most recent data points). On zoom out or pan I want the remainder of the data to be viewable. 
It seems simple enough to do but I have gotten nowhere after hours of work. Is this possible with techan?

**Comment by andredumas** [comment]
Yes it is possible. Does this do what you are asking? http://bl.ocks.org/andredumas/edf630690c10b89be390

If it does. On this line:
```
zoomableInit = x.zoomable().clamp(false).copy();
```
Add this
```
zoomableInit = x.zoomable().clamp(false).domain([<dataCountNotToShow>, data.length]).copy();
```

Refer to https://gist.github.com/andredumas/edf630690c10b89be390#file-index-html-L562

andre

**Comment by samweatherly** [comment]
Yes! That is exactly what I am looking for. 
I spent far too long trying too long trying to figure that out. 
Thank you :)
