### ISSUE TITLE
Dynamic brush

### ISSUE THREAD

**Issue by moon47usaco** [andredumas/techan.js#165]
With the current brush example it updates the translation after the brush drag is released.

Is there a way to dynamically update the chart as the brush selection is being dragged in the x direction?

Similar to how Google finance charts work: http://bit.ly/2dvHJvo

**Comment by andredumas** [comment]
Check the d3 api. For the particular example, event is triggered on brush `end`.

```
    var brush = d3.brushX()
            .extent([[0, 0], [width, height2]])
            .on("end", brushed);
```

**Comment by honzajde** [comment]
I fixed this issue by changing the event to "brush end".
