### ISSUE TITLE
Accessor API: possible to rename data keys?

### ISSUE THREAD

**Issue by briancappello** [andredumas/techan.js#168]
Use case: I'm calculating my indicators server-side, and then passing them in with the date/OHLCV values.

This code works, but it requires a lot of needless data copying on every redraw (esp as the number of indicators goes up):
```javascript
this.bbands = techan.plot.bollinger()
    .xScale(this.xScale)
    .yScale(this.yScale)

function redraw(data) {
    this.svg.selectAll('g.indicator.bbands').datum(data.map(d => (
        {date: d.date, upperBand: d.bbands_upper, middleBand: d.sma20, lowerBand: d.bbands_lower}
    ))).call(this.bbands)
}
```
I know I could do the renames on the server or on data-load, however, enough of the indicator accessors have name/key conflicts that it doesn't seem like a workable solution to me.

Would something like this be possible to implement? (Or is it already possible?)
```javascript
let bbands_accessor = techan.accessor.bollinger()
    .upper(d => d.bbands_upper)
    .middle(d => d.sma20)
    .lower(d => d.bbands_lower)
this.bbands = techan.plot.bollinger()
    .xScale(this.xScale)
    .yScale(this.yScale)

function redraw(data) {
    this.svg.selectAll('g.indicator.bbands').datum(data).call(this.bbands);
}
```

If you think it'd be a worthwhile feature and can give me some direction (like a working code example for one of the accessors), I wouldn't mind doing the work of converting the rest of the accessors and submitting the PR. (Sorry, I have yet to learn the intricacies of ES5 so I'm having trouble wrapping my head around all the mixins and binds and private-data patterns employed by your code!)

**Comment by andredumas** [comment]
That is definitely possible out of the box, it requires an additional step to the global(?) way you have it above. Every plot and indicator has a default accessor assigned. So to do this:

Either

``` javascript
let bbands_accessor = techan.accessor.bollinger()
    .upper(d => d.bbands_upper)
    .middle(d => d.sma20)
    .lower(d => d.bbands_lower)
this.bbands = techan.plot.bollinger()
    .xScale(this.xScale)
    .yScale(this.yScale)
    .accessor(bbands_accessor);
```

or

``` javascript
this.bbands_accessor = techan.plot.bollinger()
    .xScale(this.xScale)
    .yScale(this.yScale)
    .accessor()
        .upper(d => d.bbands_upper)
        .middle(d => d.sma20)
        .lower(d => d.bbands_lower) // Note this returns the accessor! Probably want to break this to obtain the plot then operate on accessor as a separate statement.
```

I do exactly like this in some instances. It was something I was going to take out at one stage, but I do find them handy at times.

Oh re the mixin's, binds and private data, nothing fancy it was just a way of trying to keep things DRY without inheritance. One of those things done in the early days never gone back to review/improve.

Will close this for now, unless a great improvement is to be made.

**Comment by briancappello** [comment]
@andredumas Hmm, those both give me `Uncaught TypeError: Cannot read property 'middle' of undefined`. However, _this_ worked:

``` javascript
        let bbands_accessor = techan.accessor.bollinger();
        bbands_accessor.upper = (d) => d.bbands_upper
        bbands_accessor.middle = (d) => d.sma20
        bbands_accessor.lower = (d) => d.bbands_lower

        this.bbands = techan.plot.bollinger()
            .xScale(this.xScale)
            .yScale(this.yScale)
            .accessor(bbands_accessor);
```

This works for me, but it's counter to the chaining convention you mentioned in one of the other issues so I figured I'd let you know!

**Comment by briancappello** [comment]
After further experimentation, the plot thickens. The syntax you mentioned _does_ work for `techan.accessor.value` and `techan.accessor.rsi`, but I couldn't get it working for bollinger, macd, or stochastic. I can't really see any differences between how the various accessors are implemented, so I'm not sure what the heck is going on. I'm starting to wonder if babel/webpack is mucking with the binding scopes? Shot in the dark hypothesis. Gonna try getting some sleep, hopefully that'll help!
