### ISSUE TITLE
error when loading data json

### ISSUE THREAD

**Issue by khunztul** [andredumas/techan.js#180]
![capture](https://cloud.githubusercontent.com/assets/13855413/20517427/8f48f7e2-b0cd-11e6-931b-f844288e4bdf.PNG)

i loaded data from json. but the chart not show and many error.
how to fix it, please help me.
thanks very much

**Comment by albertosantini** [comment]
There are many tutorials, snippets and resources showing how to use JSON with D3.js.
It is not matter of techan.js.

(Anyway it seems your data contains `NaN` values: maybe you wrongly mapped JSON data and D3.js structure).
