### ISSUE TITLE
streaming data via ajax

### ISSUE THREAD

**Issue by alexge233** [andredumas/techan.js#198]
Hi,

I realize this is more of a `d3.js` question, but I thought I'd try here first.
I've got an ajax call which loads the OHLC & Volume data (I've formatted it to send a `text/csv` but I can do any format really).
When I get the data, I've run into an issue:

```js
$.ajax({
    method: "POST",
    url: "/ajax/prices/" + symbol,
            dataType: "text"
})
.done(function(msg) {
    // msg is the actual text string containing the CSV
    d3.csv(msg, function(error, data) {
         // ERROR HERE 
    });
});
```

The `d3.csv()` does not work with my string (I am guessing it is expecting a filename).
As such, is there a way to load my data from the CSV string?
How could I populate the plot using such an approach?

**Comment by adamrabie** [comment]
if you have the data you don't need to load it. 

d3.csv **IS** the ajax call. remove your jQuery, and load your data via .csv

**Comment by alexge233** [comment]
You mean I can use the uri in the method instead of loading it via jquery?  Could you please provide an example?

**Comment by adamrabie** [comment]
https://github.com/d3/d3-request/blob/master/README.md#csv
`    d3.csv("/api/path/to/csv/response/", (err, data) => console.log(data))
`

**Comment by alexge233** [comment]
Hi @adamrabie tons of thanks!!!
