### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSeconds' of null

### ISSUE THREAD

**Issue by alexge233** [andredumas/techan.js#199]
Hi, I keep getting this error (similar to now closed issue #62).

```
Uncaught TypeError: Cannot read property 'getSeconds' of null
    at Array.<anonymous> (techan.js:4020)
    at Object.tickFormat (techan.js:4110)
    at SVGTextElement.<anonymous> (techan.js:3936)
    at SVGTextElement.<anonymous> (d3.min.js:2)
    at vt.ul [as each] (d3.min.js:4)
    at vt.hl [as text] (d3.min.js:4)
    at e (d3.min.js:2)
    at vt.nl [as call] (d3.min.js:4)
    at forecast.js:59
    at Object.<anonymous> (d3.min.js:7)
```

I'm using as template [this example](https://gist.github.com/andredumas/f9cb47fa9e32ce34011a/50127aa2cdf1959309400c22a750e9c6dae16c60) but my CSV data is formatted as YYYY-MM-DD numerically only.

I've changed the format in the example to:

```
var parseDate = d3.timeParse("%Y-%m-%d");
```

But the error still persists.
Can anyone please help?

**Comment by adamrabie** [comment]
This has nothing to do with techan, and Andre (project founder for techan) already hasn't been around for a while so please do not clog this place up with more stuff that could keep him away.

You'll need to find a mentor, hire a contractor, or put in a lot more leg work yourself into Javascript and d3. Issues are for bugs and features, not a training ground.

**Comment by alexge233** [comment]
I'm confused, is this not an issue? 
Since `techan.js` is using the underlying `d3.js` and the issue being that techan.js uses a different format, where exactly should I be asking for help, in d3.js?

**Comment by adamrabie** [comment]
Post your code or its not clear whether the issue is in usage of the libraries or the libraries themselves.
