### ISSUE TITLE
Indicators do not update after data gaps

### ISSUE THREAD

**Issue by VincentRichard555** [andredumas/techan.js#25]
Hello,

This is primarily a data issue, but it is very possible (even likely), that data gaps will occur from time to time from data providers. For example, in your data.txt file of facebook data, if you remove an open data, close data, etc. the indicators will not update after that period.

At some time, could you implement a feature that would ignore these data gaps/errors and only use full data periods so that data gaps would not cause the chart to stop updating? 

Currently, the approach I'm using is to not add these data gaps/errors into the .txt file. This should work fine, but the feature above would make the process cleaner. There is no rush because I've found a workaround for now, but this is probably necessary at some point.

Thanks for everything I really appreciate techan.js.

**Comment by andredumas** [comment]
I will close this for now. I don't think it's a common use case, some indicators need complete OHLC data to calculate, any incomplete data points should be filtered out before handing to the indicator.
