### ISSUE TITLE
In chart buy/sell arrows

### ISSUE THREAD

**Issue by smeijer** [andredumas/techan.js#33]
Should be great if there was an option to put annotation with symbols right on the candle sticks.

I wish to use such a feature to mark buy / sell orders on the graph. A red down pointing arrow to mark a sell option, and a green up pointing arrow to mark a buy option. Ofcourse, I also wish to place marks on the close-time, with the the profit or loss (result) as annotation.

**Comment by WaiSiuKei** [comment]
As for futures, it has long positions and short positions, so it will be great to have arrows to mark open-long, open-short, close-long, close-short.And a feature for indicating order filling percentage would be more appreciated.
