### ISSUE TITLE
Speed up techan.js for large (>10k) datasets

### ISSUE THREAD

**Issue by GodRtio** [andredumas/techan.js#38]
Hi @andredumas 

techan.js can't handle big dataset. techan.js can load ok with < 10K data.
But my browser freezed when load more than that. Is is because of D3 or SVG?

I do some research and find http://square.github.io/crossfilter/ can load  231,083 dataset ok.
and here proposed an solution that use css transforms: https://github.com/masayuki0812/c3/issues/774

Please let me know where i should look at the code to help?

Merry Christmas @andredumas 

GodRtio

**Comment by andredumas** [comment]
Hi @GodRtio 

Can you try the latest dev build (0.5.0-5) and let me know how you go? I've optimised the plots so for 140K points of data, rather than rendering 300k+ DOM nodes for candlestick, it will consistently only generate 6.

For testing with my much smaller datasets, this change consistently has at minimum cut render times in half. I still think 140k may still be too much for SVG, but I'd be interested to hear how it goes. I've added [this example plotting 14 years of daily data (3500 data points)](http://bl.ocks.org/andredumas/a5acb93bae58f0805b53) for reference which is also significantly more performant on the new code.

Note that this change has meant `candletick.volumeOpacity` had to be removed.

cheers
andre

**Comment by GodRtio** [comment]
@andredumas Happy New Year !!!

Wow!!! It load very fast now! How did you do it?

Thank you very much @andredumas !!!

All the Best,
GodRtio

**Comment by andredumas** [comment]
@GodRtio 

That's great to hear! In the end it was a (huge) DOM node reduction. There's some functionality that had to be removed, but I think the gain was worth the loss ;)

Will be pushing a minor change soon to make the chart look a bit clearer when plotting a lot of data.

andre

**Comment by GodRtio** [comment]
Hi @ andredumas 

I can't wait to see the next version.

I have coded a chart library using canvas, it is really fast.
But when add more layer, the more complicated the code and harder to debug. :(
So i will wait for you.

BTW, i have coded a convert timeframe function, i can group small timeframe to bigger.
Here it is:

Time = []
Open = []
High = []
Low = []
Close = []
Volume = []

//
// base TF of current Data,
// 5 = M5
// tf = number of minute
// 15 = 15
// 1 hour = 60
// 4 hour = 240
// ...
// convertTF(5, 60) will group 5 mins into 1 hour data
function convertTF(base, tf) {
    var tfOpen = [],
        tfClose = [],
        tfHigh = [],
        tfLow = [],
        tfVol = [],
        tfTime = [];

    var div = tf / base;
    var vol;
    var min, max;
    var i, j;
    var end = Time.length;

    // process lastest unfinished? data
    for (i = end - div; i < end; i++) {
        if (Time[i].getMinutes() * Time[i].getHours() % tf == 0) {
            tfTime.push(Time[i]);
            tfOpen.push(Open[i]);
            tfClose.push(Close[end - 1])

            vol = Volume[i];
            min = Low[i];
            max = High[i];

            for (j = i + 1; j < end; j++) {
                if (Low[j] < min) {
                    min = Low[j];
                }
                if (High[j] > max) {
                    max = High[j];
                }

                vol += Volume[j];
            }

            tfHigh.push(max);
            tfLow.push(min);
            tfVol.push(vol);

            break;
        }
    }

    // process data
    while (i - div > 0) {
        i -= div;

        tfTime.push(Time[i]);
        tfOpen.push(Open[i]);
        tfClose.push(Close[i + div - 1]);

        vol = Volume[i];
        min = Low[i];
        max = High[i];

        for (j = 1; j < div; j++) {

            if (Low[i + j] < min) {
                min = Low[i + j];
            }
            if (High[i + j] > max) {
                max = High[i + j];
            }

            vol += Volume[i + j];
        }

        tfHigh.push(max);
        tfLow.push(min);
        tfVol.push(vol);
    }

    // reverse data since we loop from end to start
    tfTime.reverse();
    tfOpen.reverse();
    tfHigh.reverse();
    tfLow.reverse();
    tfClose.reverse();
    tfVol.reverse();

    return {
        Time: tfTime,
        Open: tfOpen,
        High: tfHigh,
        Low: tfLow,
        Close: tfClose,
        Volume: tfVol
    };
}

Have a nice day, @andredumas 

GodRtio

**Comment by andredumas** [comment]
@GodRtio Canvas would be a lot faster, but I don't think it would ever be used for this library.

Thanks for that code snippet.

**Comment by andredumas** [comment]
@GodRtio I will close this issue for, it sounds like the main issue is now resolved.

**Comment by jankopovolny** [comment]
@GodRtio Have you re-coded techan js in canvas-style? If so, can you please share your the code?

**Comment by Micjoyce** [comment]
@GodRtio 
I open source a stock chart library using canvas, maybe you can try it, there is any question welcome. [clchart](https://github.com/seerline/clchart)
