### ISSUE TITLE
Display received technical indicator data rather than calculating it

### ISSUE THREAD

**Issue by AC90** [andredumas/techan.js#46]
Hi @andredumas,

This is a great bit of work, only came across this a few days ago and it looks like it'll be perfect for what I want - very well done. 

I have a question which is quite similar to the 'resuable framework to write own indicator' one of a month or so ago. I am calculating a number of technical indicators on the backend and what I would like is a way to get techanjs to **not** actually perform the indicator calculations (client side), but rather just take some supplied technical indicator data and display it (with a way to define the placement, scales etc).

Pls don't take this as any sort of criticism of the indicators already calculated, its just that I've got approx. 40 that are already calculated on the backend so I'm just looking for a way to display them as-is. 

I know techan is built on D3, so at some level I guess this is possible but it would be great if there is some sort of empty/template technical indicator construct into which I can just supply the data. Is anything like that possible pls ?

Tks
Alex

P.S. I should say I'm not a javascript coder so pls excuse me if this is already super easy to do and my lack of javascript makes me blind to how to do this !:)

**Comment by andredumas** [comment]
Hi Alex,

Please see [this response](https://github.com/andredumas/techan.js/issues/30#issuecomment-66980911). It partly answers your first question.

Re a template indicator project, I do plan on eventually creating this. The library is built to be testable, maintainable, internally reusable, etc, but for usages such as writing your own custom indicator there's quite a lot in the library that wouldn't be required and this may confuse most users thinking there is a need to be tightly integrated when there really isn't. A template indicator would clear this up. But I don't think it would be as simple as supplying your own data and have it magically plot, there will be some work required. There are some other libraries out there that are more configuration/data based, techanjs is geared more toward the coder.

If you already have your own data, your own indicator could be as simple as using techanjs financetime scale as a minimum dependency (for gapless date plotting) and then your own javascript and D3 plots. Other 'off the shelf' components could be used as required to short circuit development. One of the aims is to be as non-intrusive as possible. Hopefully that helps.

regards
Andre

**Comment by AC90** [comment]
ahh I hadn't previously seen the response you linked to - that is exactly my use-case. I'll have a look at trying to do something based on the accessor package (and also hunt around for some of the components to help with these plots).
Tks & rgds,
Alex

**Comment by andredumas** [comment]
No worries. Not an easy one to find. Let me know how you go.

**Comment by andredumas** [comment]
Closing, I think it was answered...
