### ISSUE TITLE
Unable to require('techanjs')

### ISSUE THREAD

**Issue by caktux** [andredumas/techan.js#47]
Best I could do was to use https://github.com/tusbar/grunt-subgrunt to run `grunt filegen`, then use `require('techanjs/src/techan')`. Any way to make this usable as a module from the start?

**Comment by andredumas** [comment]
Apart from [this test](https://github.com/andredumas/techan.js/blob/5d0b1ee7c1c8bcf453a08ba26c56b1451fb7c16f/test/spec/bundle/techanSpec.js#L5), I haven't tried using the library as a pure npm module, I assumed it should work. Briefly reviewing the code I don't think it will work and this should be tidied up.

**Comment by caktux** [comment]
Commiting `build/version.js` and adding `"main": "src/techan.js",` to package.json is probably all that's needed.

**Comment by andredumas** [comment]
I've added `main` and d3 dependency. D3 is not correctly `require`'d just yet, it is assumed to be in global scope. I'll fix this. This workaround should be enough to get you going for now:

package.json snip

```json
  "dependencies": {
    "techan": "andredumas/techan.js#bb598210d3770ef1f5fd32e05081fad231431815",
    "d3": "~3.5.3"
  }
```

Example:
```javascript
// D3 into global scope, otherwise an error will be thrown
global.d3 = require('d3');
var techan = require('techan');
console.log('d3.version', d3.version);
console.log('techan.version', techan.version);
```

I probably should look at publishing to npm registry at some stage.

**Comment by caktux** [comment]
`main` needs to point to `src/techan.js`, not `dist/techan.js`

**Comment by caktux** [comment]
You totally just ignored my comments, this is still an issue...

**Comment by andredumas** [comment]
The library was designed to be only included as a bower or npm dependency, in each case `dist/techan.js` or `dist/techan.min.js` being the entry point, hence each build has these committed. `build/version.js` shouldn't be committed. I use as both now without issue, not to say there isn't any but it is working for me.

http://bl.ocks.org/andredumas/ad585d6d68cf8a894207

**Comment by overwatch13** [comment]
When I try to reference techan when using requireJs throws and error right off the bat. I could really use this on my site, any ideas?
![techan-error](https://user-images.githubusercontent.com/8516191/36515060-ae305d3c-1745-11e8-81c3-3179302425b3.PNG)
