### ISSUE TITLE
UTC Time Scaling with financetime()

### ISSUE THREAD

**Issue by juliawalker** [andredumas/techan.js#48]
It's a question rather than an issue.  I'm new to techan.js.  With d3, I understand that I can specify the time scaling to be UTC oriented by calling, "d3.time.scale.utc()".    What are the necessary things do I need to override so time scaling of an axis as well as axis tick formatting is managed all based on UTC?

I've visited the API section on financetime() but found no documentation. 

Thanks,
Julia

**Comment by andredumas** [comment]
I've modelled financetime closely to d3.time.scale, but at the moment there's [no consideration for UTC](https://github.com/andredumas/techan.js/blob/6364ed1e23391232914e35fb312a10e3873c2e41/src/scale/financetime.js#L209).

Shouldn't be difficult to add in. I'll try to put it in next release. It will be similar API to d3:

```javascript
techan.financetime.utc();
```

**Comment by juliawalker** [comment]
Excellent!   I' really appreciate it.  Thank you.
PS:  One of the reasons why our project picked TechanJS is the features like crosshair and supstance.  They are easy to incorporate and highly value-added functionality!

**Comment by sanbor** [comment]
:+1:
