### ISSUE TITLE
Index of mouse event always zero?

### ISSUE THREAD

**Issue by prionkor** [andredumas/techan.js#52]
I am trying to add tooltip to chart. But It seem index for mouse enter event is always zero?

This is the code I am using: 

```
        svg.append("g")
                .datum(data)
                .attr("class", "candlestick")
                .on('mouseover', function(d, i){
                    console.log('Index: ' + i );
                    var d = d[i];
                    tip.html(function(){
                            var html = "<strong>Date:</strong> " + d.date + "<br>";
                            html += "<strong>Open: </strong> " + d.open + "<br>";
                            html += "<strong>High: </strong> " + d.high + "<br>";
                            html += "<strong>Low: </strong> " + d.low + "<br>";
                            html += "<strong>Close: </strong> " + d.close + "<br>";
                            return html;
                    })
                    .style({
                        left: d3.event.pageX + 20 + 'px', 
                        top: d3.event.pageY - 20 + 'px',
                        display: 'block'
                    });

                })
                .on('mouseout', function(){
                    tip.style('display', 'none');
                })
                .call(candlestick);
```

JS fiddle http://jsfiddle.net/sisir/ghox8ewa/4/ (line #79)

**Comment by andredumas** [comment]
Technically there is only 1 element ('g.candlestick') you have registered a mouseover event with which it's `__data__` is an array of data points, so it will always issue you the same data. The library also  has a [performance trade off](https://github.com/andredumas/techan.js/issues/38#issuecomment-68704476) in that each individual candle does not equal a single dom element, so tool tips using mouseover events need a little bit more work.

The two ways I generally do this is by:
* Add a clear rectangle that covers the chart, add the mousemove/mouseover event then use `var domainIndex = financetime.invertToIndex(coordinate[0])`. This result represents an index in the scale domain. Use the result to convert to your data: `data[domainIndex] // Use this value to render in your tooltip`
* Use crosshair which will do above for you. It also exposes events that pass the coordinates of the mouse which you can then use to convert to an index to obtain your data also using `financetime.invertToIndex(coord[0])` See http://bl.ocks.org/andredumas/045f550b72ad46301130. You could modify the [move callback](https://gist.github.com/andredumas/045f550b72ad46301130#file-index-html-L213) and do this processing there.

I found both of these methods to be greatly more performant than a node per plotted candle with mouse events registered to each. The chart will feel more responsive.

**Comment by andredumas** [comment]
Updated example: http://jsfiddle.net/ghox8ewa/6/

**Comment by prionkor** [comment]
Okey, if I understand correct we are now getting index of the hovered element on the dom and using it to get the data, right?
