### ISSUE TITLE
How are resizing http://techanjs.org ?

### ISSUE THREAD

**Issue by vgoklani** [andredumas/techan.js#54]
Hi,

Quick Question - how are you resizing this page: http://techanjs.org/

Is that code resizing code snippet part of your library?

Thanks,

Vishal

**Comment by andredumas** [comment]
Resizing is not part of the library, as it really depends on how the fundamental d3 chart has been constructed. I've tried to keep techanjs from forcing any particular layout style on a user and there's probably too many user implementation differences to be ever part of the library. 

In short the steps are:
* Catch a window/element resize
* [Redraw](https://github.com/andredumas/techan.js/blob/8702abb732937f823b572121c7acd5b81b52791f/src/js/index.js#L204) using standard d3 select & update techniques

```javascript
  window.onresize = function() {
    d3.select('div#chart').call(resize);
  };

  function resize(selection) {
    // Recalculate dimensions
    // Adjust scales based on new dimensions
    // Perform any other logic, change display tick count, etc
    // Redraw everything
  }
```

**Comment by chip-and-dail** [comment]
@andredumas , show your resize window code please

**Comment by lonnietc** [comment]
Greetings,

I have just gotten your Techan.js installed and am also wondering if I can see you code for resizing the plots as I would like to add it to some of your examples. In particular the examples/plot/plots example.

Can you please share this javascript code and implementation?

Thanks,
Lonnie

**Comment by chip-and-dail** [comment]
+1
