### ISSUE TITLE
financetime corrupted?

### ISSUE THREAD

**Issue by albertosantini** [andredumas/techan.js#56]
Between 5pm and `7pm`, there is not `6pm`, but `:05`
The same after `7pm`, there is `:16`

It is a feed graph and those glitches happen during the feeding, not with the initial data.

The crosshair with the annotation displays correctly the date.

Any idea?

The reference code (quite similar to your feed example):
https://github.com/albertosantini/argo/blob/master/src/client/app/components/charts.directive.js

![image](https://cloud.githubusercontent.com/assets/328179/6491249/37287d64-c2ac-11e4-97be-8b125ed44943.png)

**Comment by andredumas** [comment]
So you're expecting to see 6pm? Techan makes the best attempt to display regular ticks, but if there is no domain datum at the point where a tick should be displayed it will try to grab a logical one near it. See [here](https://github.com/andredumas/techan.js/blob/6364ed1e23391232914e35fb312a10e3873c2e41/src/scale/financetime.js#L180)

>The crosshair with the annotation displays correctly the date.

As in displays expected 6pm? What's the time format you are using in the annotation?

Are there actually data points on exactly 6pm? It would be good to see the data you are feeding in so I can see what interval it's selecting and how it's filtering the value out.

**Comment by albertosantini** [comment]
Yes, I expect 6pm. The format of the annotation is "%Y-%m-%d %H:%M".

However I think you catch the problem. 
The data doesn't point on exactly 6pm (because the ticks are not evenly distributed, as you know).

Indeed I don't see always the issue: when the volatility is high, that's there are a lot of ticks, the issue doesn't happen.

I will try to extract data to reproduce my use case.

**Comment by albertosantini** [comment]
I created a repro test:
http://jsfiddle.net/q041k8qn/

Please, see `:01` at the ending of the x axis, after `02 PM`

Noticed the mixed data: historical candles and feed ones, at the end of the time series.

**Comment by andredumas** [comment]
Yes that would be because the time isn't exactly on the hour:
```
2015-03-10T14:00:01.731Z....
```
It is choosing the 'second' formatting `:%S` producing `:01`

I don't think this is a scale corruption issue. The library probably could be smarter about the format selection. My initial thought is there may be too many user data variations to cater for everyone and it is probably simpler to leave it up to the user to specify.

In your case if techanjs is selecting roughly the correct number of ticks and they are roughly on/around the hour, you could set the d3 `axis.tickFormat` to `%I %p` or be a bit more sophisticated and supply your own formatting rules, which should give you what you need.

**Comment by albertosantini** [comment]
Agreed.

I think it is better to round my data as `2015-03-10T14:00:00.000Z`.

**Comment by albertosantini** [comment]
Indeed rounding the date properly resolved my use case.
```
...
                if (granularity === "S5") {
                    coeff = 1000 * 5;
                } else if (granularity === "S10") {
                    coeff = 1000 * 10;
                } else if (granularity === "S15") {
                    coeff = 1000 * 15;
                } else if (granularity === "S30") {
                    coeff = 1000 * 30;
                } else if (granularity === "M1") {
                    coeff = 1000 * 60;
                } else if (granularity === "M2") {
                    coeff = 1000 * 60 * 2;
...
                }

                return Math.floor(now / (coeff)) * coeff;
```
