### ISSUE TITLE
QUESTION: Candle plot based on RangeBars / Volitility based intervals. 

### ISSUE THREAD

**Issue by svenissimo** [andredumas/techan.js#60]
I'm looking to implement RangeBars ( see example: http://www.investopedia.com/articles/trading/10/range-bar-charts-different-view.asp ) and before I start building something myself I stumbled across this great suite called TechanJS ;) ..thanks

The main thing with range bars is that they are not printed at discrete time intervals like 1m, 5m etc. instead they are printed when the bar covers a predefined range..  say 25pips on the EURUSD.

I figure I can probably construct the bars elsewhere based on tick data but then when it comes to rendering them I hoped that Techan could save me some effort. Seems like the 'scale' package is a good place to start but I'm already lost. :( I should probably spend more time getting to know the innards but I'm impatient.

So..

- What would happen if I put a candle series of data in where the date/time is not at discreet intervals? would it move candles around or place them after the last one?
- would it be easier to implement an index based scale and worry about displaying the starttime of the bars later?

feel free to delete this issue/question/help if this isnt the correct forum to ask these things.

**Comment by svenissimo** [comment]
Sorry.. it seems that TechanJS will just do the right thing and puts the next bar after the previous.. which is probably due to the financial scale that removes gaps.
AWESOME.
http://jsfiddle.net/ghox8ewa/8/

**Comment by andredumas** [comment]
Glad I could help ;)

**Comment by svenissimo** [comment]
That you did, when Google highlighted your project ;) great stuff hope I can contribute one day
