### ISSUE TITLE
OHLC bar width

### ISSUE THREAD

**Issue by minkymorgan** [andredumas/techan.js#61]
Hello - a quick question - is there a way to globally set OHLC bar width as a setting? I'd like to reduce the width of bars to something skinny, somewhat like the matchstick format in quantmod. Many thanks btw for a great library. [help]

**Comment by minkymorgan** [comment]
ahh - not to worry - figured out what I wanted! thanks

**Comment by andredumas** [comment]
Nice :)

**Comment by Miserlou** [comment]
That feeling when you search for something, and the original poster has replied with "figured it out!".. >:[

Setting the stroke-width on path.ohlc doesn't appear to do anything.

@minkymorgan - what did you discover that I can't figure out? :)

**Comment by minkymorgan** [comment]
Man, I'm trying to think back. I don't have access to that code anymore. From memory I believe I swapped to using zooming, example at http://bl.ocks.org/andredumas/a48008ea8e2c832144db and then the bar width resized sensibly as needed... maybe Andre can comment?

**Comment by andredumas** [comment]
Hi @Miserlou 

OHLC gets width from the [svg path generated](https://github.com/andredumas/techan.js/blob/0.6.0/src/plot/candlestick.js#L35) with a [mixed in width function] (https://github.com/andredumas/techan.js/blob/0.6.0/src/plot/candlestick.js#L98). It's not a global setting though, just for the instance.

To change the width use:
```javascript
    var candlestick = techan.plot.candlestick()
            .width(5)
            .xScale(x)
            .yScale(y);
```
or
```javascript
    var candlestick = techan.plot.candlestick()
            .width(function(xScale) {
                return 5;
            })
            .xScale(x)
            .yScale(y);    
```

cheers
andre
