### ISSUE TITLE
Data Format Spec/Issue/Question - Javascript Error on Time Format

### ISSUE THREAD

**Issue by QRMarketing** [andredumas/techan.js#62]
A newbie, so it may be a data issue. Using JSON to get data, it seemes to be there but perhaps not in the format you need. Here is the format I was using as i see in the data array: 

[ { "Close" : 1.0998,
    "Date" : "2015-03-26 13:33:00",
    "High" : 1.10,
    "Low" : 1.0998,
    "Open" : 1.0998
  }, .....

data:
Array[2000][0 … 99]0: Object Close: 1.0998
                                    Date: "2015-03-26 13:33:00"
                                    High: 1.1
                                     Low: 1.0998
                                    Open: 1.0998

index.html:

<code>
    d3.json("http://xyz.com/JSON-INIT.php?i=EURUSD", function(error, data) {
        var accessor = candlestick.accessor();

        data = data.slice(0, 200).map(function(d) {
            return {
                date: parseDate(d.Date),
                open: +d.Open,
                high: +d.High,
                low: +d.Low,
                close: +d.Close
            };
        }).sort(function(a, b) { return d3.ascending(accessor.d(a), accessor.d(b)); });
</code>

Techan.js:
<code>
 var dayFormat = d3_time.format('%b %e'),
      yearFormat = d3_time.format.multi([
        ['%b %Y', function(d) { return d.getMonth(); }],
        ['%Y', function() { return true; }]
      ]),

      intraDayFormat = d3_time.format.multi([
        [":%S", function(d) { return d.getSeconds(); }],   // Uncaught TypeError: Cannot read property 'getSeconds' of null

        ["%I:%M", function(d) { return d.getMinutes(); }], 
        ["%I %p", function (d) { return true; }]
      ]),
</code>

**Comment by andredumas** [comment]
Hard to tell what the problem could be there, but the error does imply that date is null. Can you create a gist or jsfiddle recreating the issue?

Also ensure parseDate is returning a non null value for ALL values in the data set. It could be that you have a single date or line that is ending up being null

**Comment by QRMarketing** [comment]
No it not null, its D3 plays games with the data object, timezones etc.... The data I populate gets transformed into a magical time object that then messes every thing up. But at the end of the day, the issue is that I am trying to understand the code you wrote and being a newbie this takes longer than if I just started from scratch and go through the pain, starting from ground up. This way I learn what is going on and can fix it. 

I saw another package and it was good too, but I ran into issues that I could not fix and bailed because the code was deep. I think to make a libraries that people can use, it has got to be idiot proof for the mass newbie coders like me and well explained and documented. Otherwise it is a stand alone package, that looks good, but you just have to be really good to work with it. 

Thanks for answering, you have done some good work, but you will have to idiot proof it and make interfaces to it that are simple. This is not such a fun project as it is not really technical, its is just more of the approach you take when building software for potential wider use.

But I got a lot of good ideas looking at your code, so thanks for this. I am about 50% to where you are at, but doing it in a newbie way and more simplier, though for sure you would laugh at the code.

Thanks again ....

**Comment by gr1212** [comment]
Hi, 
Had a similar issue. I fixed it by setting my csv dates to: 
24-Aug-15 08:00:00,0

and I set the Techan date format to: 
var parseDate = d3.time.format("%d-%b-%y %I:%M:%S").parse,
          timeFormat = d3.time.format('%Y-%m-%d %I:%M:%S'),
          valueFormat = d3.format(',.2fs');

I found this url quite handy:
http://bl.ocks.org/zanarmstrong/raw/ca0adb7e426c12c06a95/

**Comment by QRMarketing** [comment]
Nice cheat sheet thanks. I kind of went in a different direction. You can check out my App here:
Click the button to trade. It has a demo mode where you can trade demo ......I have a trade engine back end. https://www.micro-prop-shop.com/

**Comment by andredumas** [comment]
Don't think this is an issue with the library.

**Comment by gr1212** [comment]
What would be handy is a simple example using: 
1) Typical JSON format (http://stackoverflow.com/questions/10286204/the-right-json-date-format) namely ISO 8601 (i.e. 2012-04-23T18:25:43.511Z)
2) Hourly data (most of the samples on the site use daily's)

**Comment by QRMarketing** [comment]
"Don't think this is an issue with the library." Well yes and no. The probem is that the plugin can only be used in a clean page with nothing else on it. Otherwise it won't work. It needs to be implemented in a way where there are no conflicts. People that have no control over the other parts of the page can use it.

**Comment by andredumas** [comment]
I'm not sure I know what you mean by 'clean page'. I've used techanjs mixed in with quite a number of different libraries, with multiple different charts on a single page without issue. I'm quite sure you would've experienced a similar error if you were to use a raw d3 time scale.

techanjs makes minimal assumptions about a users source data, and those assumptions can also be customised if required, but at minimum when dealing with dates in javascript the object needs to be a date. Keep in mind JSON is a text format

As initially mentioned ensure all dates are parsing and are actually javascript date objects.
