### ISSUE TITLE
How would you make make volume charts thinner?

### ISSUE THREAD

**Issue by prionkor** [andredumas/techan.js#65]
I have a chart which is very much how the candlestick and volume charts are in the example of techanJS.

I am looking to make the volume bar width very thin (for example 3px). Example: **notice the red volume lines** 

![techan volume](http://i.imgur.com/2lTkLkd.jpg)

I have tried to track down the source code of techan where the volume width has been set. But I was unsuccessful. 

**Off topic:** Can we open a stackoverflow tag for techan-js? It would be best to ask this types of question there with tagging.

**Comment by andredumas** [comment]
Hi @prionkor 

This currently isn't supported out of the box but is something I have been considering for a while: #13 

Stackoverflow tag would be great, though I don't have priv's to create one. Also tag named "techanjs" as opposed to "techan-js" seems to be more in line with the other js projects.

cheers
andre

**Comment by prionkor** [comment]
Sadly I can't make a tag on so yet. Hope someone get to it soon. BTW, any idea when the compatibility might be added in future?
