### ISSUE TITLE
How to Format Date for Weekly, Monthly & Yearly CandleStick?

### ISSUE THREAD

**Issue by prionkor** [andredumas/techan.js#66]
[Looking at data structure](https://github.com/andredumas/techan.js/wiki/Data-Structures#ohlc--volume) for OHLC Examples requires full date value.

In the case of weekly, monthly or yearly candlestick, ohlc chart how should I format data?

**Comment by prionkor** [comment]
Can someone please reply on this? I have a deadline monday. need it asap :(

**Comment by prionkor** [comment]
@PSzu So basically what we input as a date is start of the week day? For example 

````
Date,Open,High,Low,Close,Volume
date1 , 62.40,63.34,61.79,62.88,37617413
date2 , 62.40,63.34,61.79,62.88,37617413
````

Where `date1` is the first day of the week and `date2` is the first day of the next week?

**Comment by PSzu** [comment]
@prionkor some providers use Mondays and some use Fridays for the weekly data. I guess the most important is that the dates do not overlap within the same week. Once you choose Mondays, use Mondays only.

**Comment by prionkor** [comment]
Thanks for shedding light on this. Really appreciate it!!

**Comment by andredumas** [comment]
Hi @prionkor 

How's it going with this? 

I will post some sample code of how I'd do it at some stage. May incorporate it in the core as well.

cheers
andre

**Comment by prionkor** [comment]
I have done as I commended. 

For weekly `monday_date, week_open, week_high, week_low, week_close`
For monthly `first_day_date, month_open, month_high, month_low, month_close`

I don't know if this is the standard though.
