### ISSUE TITLE
logarithmic price scale charts

### ISSUE THREAD

**Issue by PSzu** [andredumas/techan.js#67]
First of all this library is absolutely fantastic. Do you have any plans for logarithmic price scale charts? I am missing this feature to draw long-term trend lines.

**Comment by prionkor** [comment]
Sorry for the unrelated comment. If you know solution of this https://github.com/andredumas/techan.js/issues/66 let me know. The programmer of he repo is offline for last 3+ weeks.

**Comment by PSzu** [comment]
@prionkor the last commit from Andre Dumas was yesterday https://github.com/andredumas/techan.js/commit/5197278f7936d67bacd610c2fabf776d19b2c626

If you do need to convert data from daily to monthly and weekly and your data is static, the easiest way is to use python pandas, see http://pandas.pydata.org/pandas-docs/dev/timeseries.html#up-and-downsampling.

To makes things easy you may also want to download a sample from any website that provides csv data for financial instruments. For example: http://stooq.pl/q/d/l/?s=xagusd&d1=20150301&d2=20150528&i=w

This is a weekly data for silver since 01/03/2015. You can use the website or modify links to get desired data and change daily, weekly and monthly format. As you can see the date for the weekly candles is Friday in this case and the last day of month for monthly data.

**Comment by prionkor** [comment]
@PSzu Replied on my ticket.

**Comment by andredumas** [comment]
hi @PSzu 

Not at the moment. I don't use that, but drop an image sample here as a feature request.

cheers
andre

**Comment by moconnell** [comment]
+1 vote

**Comment by ctwhome** [comment]
+1 and also say that this library looks fantastic!

**Comment by briancappello** [comment]
@PSzu @moconnell @ctwhome 
FYI this works out-of-the-box; it's a feature of ``d3`` rather than ``techan.js``.

In all of the example codes, just replace
```javascript
var y = d3.scaleLinear()
            .range([height, 0]);
```
with
```javascript
var y = d3.scaleLog()
            .range([height, 0]);
```

**Comment by andredumas** [comment]
Thanks for the comment @briancappello. Out of the box d3 is always preferred. Please close this issue if it meets your requirements.

**Comment by PSzu** [comment]
Thank you @briancappello @andredumas . This is fantastic news. I have not been available for a while and did not notice the comment. I am setting the issue as resolved.

**Comment by icastillejogomez** [comment]
Great issue! Thank all!
