### ISSUE TITLE
X axis labels overlap in small screen

### ISSUE THREAD

**Issue by sf-wind** [andredumas/techan.js#76]
It is okay to skip label for some entries. Any idea to fix this? 

![screen shot 2015-06-27 at 12 45 56 am](https://cloud.githubusercontent.com/assets/4585741/8391046/e4684532-1c65-11e5-90ce-454efe43e3b8.png)

**Comment by andredumas** [comment]
@sf-wind This is standard d3 functionality.

http://techanjs.org/ does this exactly. Resize the window smaller.

http://bl.ocks.org/andredumas/274b54b4d2c2ffa19fca also does this. See https://gist.github.com/andredumas/274b54b4d2c2ffa19fca#file-index-html-L128
