### ISSUE TITLE
Does supstance expose the change data after it being dragged?

### ISSUE THREAD

**Issue by sf-wind** [andredumas/techan.js#77]
One can drag the supstance to a different position. Can the new position value be retrieved? Thanks.

**Comment by andredumas** [comment]
@sf-wind See example http://bl.ocks.org/andredumas/10194a84a3e46fe127d4

Handlers can be added: 
https://gist.github.com/andredumas/10194a84a3e46fe127d4#file-index-html-L195
and
https://gist.github.com/andredumas/10194a84a3e46fe127d4#file-index-html-L212
