### ISSUE TITLE
Min height for candle

### ISSUE THREAD

**Issue by akuz** [andredumas/techan.js#82]
Hi, I have a case when the value doesn't change at all within a candle on a candlestick diagram. The candlestick layout, I guess, currently sets the height of the respective candle to 0px, and so nothing is visible at all for this candle. It would be nice if it could be set to 1px instead, and the colour can be set using "candle.nochange" (or some other name) CSS class. What do you think?

**Comment by andredumas** [comment]
techan.js already supports [this](https://github.com/andredumas/techan.js/blob/d1efb6e7909fc7235d95045100e5f2199e7f94af/src/plot/candlestick.js#L81)

Refer to [candlestick example](http://bl.ocks.org/andredumas/27c4a333b0e0813e093d). There is an `path.candle.body.equal` that can be individually styled.
![equal-candle](https://cloud.githubusercontent.com/assets/1518740/11019541/b25d54fa-8651-11e5-9b87-c995fed47048.png)
