### ISSUE TITLE
OHLC domain not calculated properly

### ISSUE THREAD

**Issue by akuz** [andredumas/techan.js#84]
Candlestick OHLC domain is calculated based on close value. If the values go strictly down in all candles, this causes the top of the first candle to go off the chart.

**Comment by andredumas** [comment]
I don't think this is correct. Unless it's a defect. Provide jsfiddle of your observation.

Refer to: [OHLC domain utility method using low and high](https://github.com/andredumas/techan.js/blob/5b3446e3ac68b5666ab22e8f3c688a976a0f9c79/src/scale/index.js#L63)
