### ISSUE TITLE
xAxis Datetime display issue

### ISSUE THREAD

**Issue by fhmkryl** [andredumas/techan.js#85]
I'm new to techan.js charts. Trying to use candlesticks chart however cannot display full date time on xAxis. 

For instance i want to show 2015/09/01 23:11, but it onlys shows 2015/09/01 part. Is there any way to show full time in  %Y/%m/%d %H:%M  format on xAxis?

**Comment by andredumas** [comment]
Where possible I've followed standard D3 conventions for changing tick format, this should be possible. It should work in the same way. Also without jsfiddle or gist, it's difficult to see what you are trying to do.
