### ISSUE TITLE
How to set minimum brush size?

### ISSUE THREAD

**Issue by DaZzz** [andredumas/techan.js#87]
Currently I'm implementing [this example](http://bl.ocks.org/andredumas/a5acb93bae58f0805b53), but with a bit of react.

Here is the function that does redrawing. It's a part of react component.

```js
  redrawChart() {
    let {
      x, y, x2, y2, xAxis, xAxis2, yAxis, yAxis2,
      height2, yVolume, candlestick, volume, close,
      focus, context, brush, zoomable, zoomable2, mask
    } = this.chartProps

    let candlestickSelection = focus.select('g.candlestick')
    let data = candlestickSelection.datum()

    mask.reveal(brush.empty() ? zoomable2.domain() : brush.extent())

    zoomable.domain(brush.empty() ? zoomable2.domain() : brush.extent())
    y.domain(techan.scale.plot.ohlc(data.slice.apply(data, zoomable.domain()), candlestick.accessor()).domain())

    let [from, to]   = brush.extent()
    let [minX, maxX] = brush.x().domain()
    mask.reveal([(from - minX)/(maxX - minX), (to - minX)/(maxX - minX)])

    candlestickSelection.call(candlestick)
    focus.select('g.volume').call(volume)
    focus.select('g.x.axis').call(xAxis)
    focus.select('g.y.axis').call(yAxis)
    context.select('g.close').call(close)
    context.select('.extent')
      .attr('rx', 2)
      .attr('ry', 2)
  }
```

I thought that I need to use this [common technique](http://bl.ocks.org/raffazizzi/3691274).

```js
    var s = d3.event.target.extent();
    if (s[1]-s[0] < 0.5) {
        var start = Math.round((data.length-1)*s[0]);
        var end = Math.round((data.length-1)*s[1]);

        bar(data.slice(start,end));
    }
    else {
        d3.event.target.extent([s[0],s[0]+0.5]);
        d3.event.target(d3.select(this));
    }
```

But I have problems setting new extent and firing `d3.event.target(d3.select(this))` due to the fact that `financetime().zoomable()` is an object and cannot be called.

How would you implement brush size limitation and is it possible right now? Could you provide an example using  [TechanJS Brush block.](http://bl.ocks.org/andredumas/a5acb93bae58f0805b53)

Thanks!

**Comment by andredumas** [comment]
Hmmm... 
> financetime().zoomable() is an object and cannot be called.

Now that's a slight oversight on my behalf... Guess I've never needed to use it that way.

What is the error? Would you have a harness or a jsfiddle I could have a play with?
