### ISSUE TITLE
MACD and Signal lines mixed up?

### ISSUE THREAD

**Issue by chrisdrusso** [andredumas/techan.js#89]
Fantastic work!  Are the macd and signal paths mixed up?  I understood that the signal should be the shorter term average.  However the path.signal in the css appears to apply to the longer term average.

    path.macd {
        stroke: #0000AA;
    }

    path.signal {
        stroke: #FF9999;
    }

**Comment by andredumas** [comment]
I don't think so? Signal line is EMA of the MACD, so it should be lagging. Unless i'm missing something.

From tradingview:
![tradingview-fb](https://cloud.githubusercontent.com/assets/1518740/11019306/19343176-8648-11e5-933b-4761b772ab6f.png)

techan.js:
![techanjs-macd-fb](https://cloud.githubusercontent.com/assets/1518740/11019483/8c66c2ac-864e-11e5-99c2-fe6711929c21.png)

andre

**Comment by chrisdrusso** [comment]
You are correct.  The signal should be lagging.  Thanks.
