### ISSUE TITLE
My Solution for: How to make  snapshot or save the chart to harddisc?

### ISSUE THREAD

**Issue by linuxorg1** [andredumas/techan.js#94]
My Solution:
1. https://github.com/exupero/saveSvgAsPng
Installation
npm install save-svg-as-png
Usage
To save a PNG, include the script saveSvgAsPng.js in your page, then call the saveSvgAsPng function with an SVG node and a filename:
saveSvgAsPng(document.getElementById("diagram"), "diagram.png");

2. in File index.html search for draw()
append save Function like

        draw();
        // Associate the zoom with the scale after a domain has been applied
        zoom.x(zoomable).y(y);
        zoomPercent.y(yPercent);
		saveAsPng();

3. fucntion saveAsPng():

function saveAsPng() {
	document.getElementsByTagName('svg')[0].id = 'mysvg';

	saveSvgAsPng(document.getElementById("mysvg"), "diagram.png");
}   
This line is very Importent for svg id
document.getElementsByTagName('svg')[0].id = 'mysvg';

**Comment by andredumas** [comment]
Thanks for the suggestion but you already created #90 with this same comment. Please keep the issues for raising defects and feature requests.

This would be better in a blog post, feel free to do that :)
