### ISSUE TITLE
Graphical glitches whith grid and annotation

### ISSUE THREAD

**Issue by zDemoniac** [andredumas/techan.js#97]
When I set .innerTickSize() in d3.svg.axis() some annotation becomes glitched

Here is jsFiddle, based on sample "TechanJS Axis Annotation", I'm only add 2 line with .innerTickSize()

http://jsfiddle.net/zDemoniac/21mxeL3q/4/

So, if remove line 19 and line 28 -- no glitches, but also no grid :)

**Comment by zDemoniac** [comment]
So, if remove line 19 and line 28 -- no glitches, but also no grid :)

**Comment by andredumas** [comment]
That should be fixed.

Thanks for the jsfiddle, = faster turnaround time.

**Comment by zDemoniac** [comment]
Yes, work great! Thanks for very fast fix.
