### ISSUE TITLE
Overlap Issue with x-Axis ticks in small screens

### ISSUE THREAD

**Issue by anelliot** [andredumas/techan.js#99]
We're trying to use this library for a project that involves small window sizes. In your examples, the window is hardcoded at 950. Any smaller size seems to cause some overlap issues in the axis labels. This seems to possible have something to do with the math in the tickMethod() function, but I'm not sure. Any help or direction you could give on this would be great. 

![screenshot_20151117-171508](https://cloud.githubusercontent.com/assets/14337623/11229923/440d8cd6-8d4f-11e5-99d0-32d87d52f1d4.png)

**Comment by chip-and-dail** [comment]
@andredumas Please, add the resize method. You have it.

**Comment by andredumas** [comment]
Nice colors :)

This falls back to standard D3 logic. I believe you'd encounter the same issue using any other D3 scale and axis. Tick count on the axis has to be reduced. It defaults, as D3 does, to 10.

Refer to example: http://bl.ocks.org/andredumas/274b54b4d2c2ffa19fca

Specifically https://gist.github.com/andredumas/274b54b4d2c2ffa19fca#file-index-html-L128

Also: https://github.com/mbostock/d3/wiki/SVG-Axes#ticks

For resizing I dynamically recalculate the optimum tick count based on width.

andre
